Watching for file changes with StatReloader
Watching for file changes with StatReloader
Error: That port is already in use.
/home/teenah/web1/lab1/core/settings.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
July 08, 2024 - 03:49:55
Django version 5.0.6, using settings 'core.settings'
Starting development server at http://10.0.0.98:8080/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
/home/teenah/web1/lab1/core/urls.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
July 08, 2024 - 04:38:14
Django version 5.0.6, using settings 'core.settings'
Starting development server at http://10.0.0.98:8080/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/teenah/web1/myenv/lib/python3.12/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/teenah/web1/myenv/lib/python3.12/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/home/teenah/web1/myenv/lib/python3.12/site-packages/django/core/management/base.py", line 486, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/home/teenah/web1/myenv/lib/python3.12/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teenah/web1/myenv/lib/python3.12/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teenah/web1/myenv/lib/python3.12/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "/home/teenah/web1/myenv/lib/python3.12/site-packages/django/urls/resolvers.py", line 519, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "/home/teenah/web1/myenv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/teenah/web1/myenv/lib/python3.12/site-packages/django/urls/resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/teenah/web1/myenv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/teenah/web1/myenv/lib/python3.12/site-packages/django/urls/resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/teenah/web1/lab1/core/urls.py", line 19, in <module>
    from .views import home_page_view
ModuleNotFoundError: No module named 'core.views'
/home/teenah/web1/lab1/core/urls.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
[08/Jul/2024 04:41:10] "GET / HTTP/1.1" 200 13
/home/teenah/web1/myenv/lib/python3.12/site-packages/sqlparse/filters/right_margin.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
July 08, 2024 - 04:40:43
Django version 5.0.6, using settings 'core.settings'
Starting development server at http://10.0.0.98:8080/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
/home/teenah/web1/myenv/lib/python3.12/site-packages/asgiref/__init__.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
July 08, 2024 - 19:12:24
Django version 5.0.6, using settings 'core.settings'
Starting development server at http://10.0.0.98:8080/
Quit the server with CONTROL-C.

Traceback (most recent call last):
  File "/home/teenah/web1/lab1/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
  File "/home/teenah/web1/myenv/lib/python3.12/site-packages/django/core/management/__init__.py", line 17, in <module>
  File "/home/teenah/web1/myenv/lib/python3.12/site-packages/django/conf/__init__.py", line 17, in <module>
ImportError: cannot import name 'global_settings' from partially initialized module 'django.conf' (most likely due to a circular import) (/home/teenah/web1/myenv/lib/python3.12/site-packages/django/conf/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/teenah/web1/lab1/manage.py", line 22, in <module>
    main()
  File "/home/teenah/web1/lab1/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Error: That port is already in use.
Watching for file changes with StatReloader
[09/Jul/2024 20:17:50] "GET /login/?next=/ HTTP/1.1" 200 9544
[09/Jul/2024 20:18:06] "GET / HTTP/1.1" 302 0
[09/Jul/2024 20:18:06] "GET /login/?next=/ HTTP/1.1" 200 9544
Watching for file changes with StatReloader
Error: That port is already in use.
Watching for file changes with StatReloader
Error: That port is already in use.
[09/Jul/2024 20:21:10] "GET / HTTP/1.1" 200 13
Not Found: /favicon.ico
[09/Jul/2024 20:21:10] "GET /favicon.ico HTTP/1.1" 404 2268
[09/Jul/2024 20:21:11] "GET / HTTP/1.1" 200 13
[09/Jul/2024 20:21:19] "GET / HTTP/1.1" 200 13
[09/Jul/2024 20:58:38] "GET / HTTP/1.1" 200 13
[09/Jul/2024 21:00:58] "GET / HTTP/1.1" 200 13
